/**
 * Константы для панели
 */

export const DASHBOARD_SHOW_NOTICE = 'DASHBOARD_SHOW_NOTICE'
export const DASHBOARD_HIDE_NOTICE = 'DASHBOARD_HIDE_NOTICE'
export const DASHBOARD_SET_SIDEBAR_STATE = 'SET_SIDEBAR_STATE'
export const DASHBOARD_SET_MOBILE_SIDEBAR_STATE = 'SET_MOBILE_SIDEBAR_STATE'
export const DASHBOARD_SIDEBAR_STATE_EXPANDED = 'EXPANDED'
export const DASHBOARD_SIDEBAR_STATE_COLLAPSED = 'COLLAPSED'

export const DASHBOARD_NOTICE_VISIBLE = true
export const DASHBOARD_NOTICE_HIDDEN = true
